DjangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    # path('',include('myapp.urls'))
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views
from . views import QuestionsListView


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('home/', QuestionsListView.as_view(), name='home'),
    path('home/<int:qid>', views.answer_view, name='answer'),
    path('',views.HomePage_view,name='homepage'),
    path('fetch/',views.fetch_results,name='fetch_results'),

]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Question(models.Model):
    question = models.TextField()

    # should we add timelimit and wordcount to this?

    def __str__(self):
        return "{}".format(self.question)


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()
    score = models.FloatField()

myapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from . models import Answer


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super(MyUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        print(user.password)
        if commit:
            user.save()
        return user


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["answer"]
    paused_time = forms.CharField(widget=forms.HiddenInput)

myapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.mixins import
from django.views.generic import ListView
# Create your views here.
from django.urls import reverse_lazy
from django.views import generic
from . forms import MyUserCreationForm, AnswerForm
from . models import Question, Answer
from django.http import HttpResponse
from .checker.report import Report
import json
#from . misc import score_calculator


class SignUp(generic.CreateView):
    form_class = MyUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class QuestionsListView(ListView):
    template_name = "home.html"
    model = Question


def HomePage_view(request):
    return render(request,template_name="homepage.html")

# class AnswerView(generic.CreateView):
#     model = Answer
#     fields = ["answer"]
#
#     def form_valid(self, form):
#         answer_object = form.save(commit=False)
#         answer_object.user = self.request.user
#         answer_object.question =

@login_required(login_url="login")
def answer_view(request, qid):
    # case where question doesn't exist? return a 404 error
    context = {"submitted": False, "question": Question.objects.get(pk=qid), "paused_time": '', "results": None}
    if request.method == "POST":
        # print("IN POST")
        form = AnswerForm(request.POST)
        if form.is_valid():
            # print("IN POST")
            # print(form)
            context["submitted"] = True
            context["paused_time"] = form.cleaned_data["paused_time"]  #
            answer_object = form.save(commit=False)
            answer_object.user = request.user
            answer_object.question = context["question"]
           # answer_object.score = results["score"]
            answer_object.save()
    else:
        form = AnswerForm()
        # print("IN GET")
    context["form"] = form
    # print(request.method,context)
    return render(request, template_name="answer.html", context=context)


def fetch_results(request):
    if request.method == "GET":
         return HttpResponse("hey") 
    if request.method == "POST":
        d = Report(request.POST['essay']).reprJSON()
        return HttpResponse(json.dumps(d))
    #return render(request,template_name="answer.html",context={"obj":json.dumps(d)})

myapp/templates/answer.html
{% load static %}
<!DOCTYPE html> {% load bootstrap4 %}
<html lang="en">

<head>
    <tag autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Essay Checker</title>
</head>
<link rel="stylesheet" href="{% static "answer.css"%}"/>

<body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2">
                <a class="navbar-brand d-inline-block align-top" href="#">
                    <img src="{% static "images/correct.png" %}" width="35" height="35" alt="">
                    <a id="homelink" href="{% url "homepage" %}"><span>Grammar Expert</span></a>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                  <a class="nav-item nav-link pr-5">Hi {{ user.username }}!</a>
                  <a class="nav-item nav-link pr-2" href="{% url "logout" %}">Logout</a>
                </div>
              </div>
            </nav>
    <div class="container">
        <div class="row">
                <h3 class="col-sm-8 col-md-8">{{ question.question }}</h3>
                <h4 class="col-sm-3 col-md-3" id="time"></h4>
        </div>
        <div class="row">
            <div class="col-sm-1 col-md-1"></div>
            <textarea class="col-sm-10 col-md-10" id="id_answer" rows="20" cols="120" placeholder="Write your essay here"></textarea>

            <p class="col-sm-10 col-md-10" id='essay'></p>
            <div class="col-sm-1 col-md-1"></div>
        </div>
        <div class="row">
            <div class="col-sm-2 col-md-2"></div>
            <h4 class="col-sm-4 col-md-4" id="wordcount"></h4>
            <button class="col-sm-4 col-md-4 btn btn-primary btn-lg" type="button"
                    id="submit_button">Submit</button>
        </div>
        <div class="row" id="res">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>Overall Score</th>
                        <td id="score"></td>
                    </tr>
                    <tr>
                        <th>Word Count</th>
                        <td id="w_c"></td>
                    </tr>
                    <tr>
                        <th>Grammar Errors</th>
                        <td id="grammar"></td>
                    </tr>
                    <tr>
                        <th>Spelling Mistakes</th>
                        <td id="spelling"></td>
                    </tr>
                    <tr>
                        <th>Word Limit Check</th>
                        <td id="wordlimit">Essay does not meet required word limit</td>
                    </tr>
                </tbody>
            </table>
        </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static "answer.js" %}"></script>

</html>

myapp/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

myapp/templates/home.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body{
            font-family: 'Ubuntu', sans-serif;
            letter-spacing: 0.0500em;
        }
        .navbar-brand span{
            padding-left: 15px;
            font-family: 'Raleway', sans-serif;
            letter-spacing: 0.0800em;
        }
        .card{
            border-radius: 0;

        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2">
        <a class="navbar-brand d-inline-block align-top" href="#">
            <img src="{% static "images/correct.png" %}" width="35" height="35" alt="">
            <span>Grammar Expert</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link pr-5">Hi {{ user.username }}!</a>
          <a class="nav-item nav-link pr-2" href="{% url "logout" %}">Logout</a>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
      <div class="row">
        <div class="col-md-9">
        {% for question in object_list %}
          <div class="card">
            <div class="card-body d-flex flex-wrap">
                <p class="card-text col">{{ question }}</p>
                <a href="{% url 'answer' question.id %}"><button class="btn btn-success my-auto">attempt</button></a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Grammar Expert</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .container p{
            color: #edf3f5;
            font-family: 'Ubuntu', sans-serif;
            font-size: 45px;
            letter-spacing: 0.0500em;
            z-index: 2;
            text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
        }
        .navbar-brand span{
            padding-left: 15px;
            font-family: 'Raleway', sans-serif;
            letter-spacing: 0.0800em;
        }
        body {
            background: url('https://www.netgeekpro.com/wp-content/uploads/2017/06/Best-Laptop-For-Writers-Writing.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            background-size: cover;
            -o-background-size: cover;
        }


    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2">
        <a class="navbar-brand d-inline-block align-top" href="#">
            <img src="{% static "images/correct.png" %}" width="35" height="35" alt="">
            <span>Grammar Expert</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link pr-5" href="{%url "login"%}">Login</a>
          <a class="nav-item nav-link pr-2" href="{%url "signup"%}">Signup</a>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
            <p class="text-center font-weight-light">Put your grammar skills to test</p>
{#            <form method="post">#}
{#                {{ form.as_p }}#}
{#            </form>#}
    </div>
</nav>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/signup.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <style>
        body{
          background-color: snow;
        }
        body,input{
            font-family: 'Ubuntu', sans-serif;
            letter-spacing: 0.0800em;
        }
        {
            font-family: 'Ubuntu', sans-serif;
            letter-spacing: 0.0800em;
        }
        label{
            display: none;
        }
        ul{
            display: none;
        }
        .navbar-brand span{
            padding-left: 15px;
            font-family: 'Raleway', sans-serif;
            letter-spacing: 0.0800em;
        }
    </style>
</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2">
        <a class="navbar-brand d-inline-block align-top" href="#">
            <img src="{% static "images/correct.png" %}" width="35" height="35" alt="">
            <span>Grammar Expert</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link pr-5" href="{% url "login" %}">Login</a>
          <a class="nav-item nav-link pr-2" href="{% url "homepage" %}">Home</a>
        </div>
      </div>
    </nav>


    <div class="container">
        <div class="row-1">
            <div class="d-flex flex-column col-sm-9 col-md-7 col-lg-5 mx-auto my-5">
                <div class="card card-signup p-2">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" name="commit" value="Signup" tabindex="3" class="btn btn-primary btn-block" data-disable-with="Logging in…">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>